### ISSUE TITLE
Upload version 3.0 and allow PR to version 4.0

### ISSUE THREAD

**Issue by jobisoft** [mschoettle/toggle-headers#2]
This is of cosmetic nature. It would be great if you could upload version 3 in a different branch and allow me to make a public PR with my changes for version 4.0. Thanks!

**Comment by mschoettle** [comment]
I tried to attribute the contribution (see #1) to you but could not find your user. Is your goal to have this be attributed to your user? I could try to add a `Co-Authored-By: ` to the commit (since the repo is new and no one else has most likely cloned this yet).

Would that help?

**Comment by jobisoft** [comment]
Yes, it is to keep track of my public work, as it is paid for by Thunderbird. The `Co-Authored-By:` attribution would be perfect. Thanks!

**Comment by mschoettle** [comment]
That makes sense. I tried to find your user using your Thunderbird email address but could not find it. If it's not in your profile maybe you could add it as a secondary email address?

I retroactively changed the commit via a rebase. Normally not something one should do on a public branch but I deemed it was okay in this case.

See commit 804a49d7f2fb8ae2672f69aa66027746baf4f25c
